Sim
SOMAS2020/SOMAS-Final-Report pull request #34
Opened 2021-01-12 20:06 UTC by NGovani

Initial simulation commit, sets the format for how metrics should be presented in future analysis

2021-01-12 21:01 UTC, ezgimez commented
can @yp717  check this PR plz?

if @yp717  is unavailable, I can check this PR _belatedly_ cuz I'm in deep IIGO stuff now

2021-01-12 21:48 UTC, lhl2617 commented on 15_simulations/index.tex
> +The purpose of performing simulations and analysing their results is to explore the efficacy of each agent's strategy under different conditions. We would like to answer questions such as: does the b
analyses encapsulate or analysis encapsulates

2021-01-12 21:48 UTC, lhl2617 commented on 15_simulations/index.tex
> +The purpose of performing simulations and analysing their results is to explore the efficacy of each agent's strategy under different conditions. We would like to answer questions such as: does the b
all the work ~we have put in~ done

2021-01-12 21:48 UTC, lhl2617 commented on 15_simulations/index.tex
> +The purpose of performing simulations and analysing their results is to explore the efficacy of each agent's strategy under different conditions. We would like to answer questions such as: does the b
~display~displaying

2021-01-12 21:49 UTC, lhl2617 commented on 15_simulations/index.tex
> +The purpose of performing simulations and analysing their results is to explore the efficacy of each agent's strategy under different conditions. We would like to answer questions such as: does the b
how ~behaviors~?

2021-01-12 21:50 UTC, lhl2617 commented on 15_simulations/index.tex
> +    \item \textbf{Island Resources$^1$$^2$}: Resource an island has each turn
```suggestion
    \item \textbf{Island Resources$^1$$^2$}: Resource an island has each turn.
```

2021-01-12 21:50 UTC, lhl2617 commented on 15_simulations/index.tex
> +To assist in this analysis we need to draw quantifiable results from the simulations. Thus enters the metrics, these numerical values or visualisation give us information on the events of the game th
```suggestion
To assist in this analysis we need to draw quantifiable results from the simulations. Thus enters the metrics: these numerical values give us information on the events of the game that we can then use to compare numerous simulations and draw insights into what effect the changing of certain parameters has on the game. Some metrics are also worth knowing on a turn by turn basis and as such have been represented as graphs. 
```

2021-01-12 21:51 UTC, lhl2617 commented on 15_simulations/index.tex
> +    \item \textbf{First Island Death}: Turns until a single island dies.
```suggestion
    \item \textbf{First Island Death}: Turns until any island dies.
```

(two islands can die in the same turn)

2021-01-12 21:51 UTC, lhl2617 commented on 15_simulations/index.tex
> +In order to make any meaningful analysis one must first have baseline from which to compare. In our case, this baseline is a 'normal' set of environment conditions which allow the agents to thrive fo
```suggestion
In order to make any meaningful analysis one must first have baseline from which to compare. In our case, this baseline is a \emph{normal} set of environment conditions which allow the agents to thrive for a significant period of time, around 100 turns. From this baseline we can then start adjusting the configuration of the simulation, either making disaster more frequent/deadly, or making resources more sparse.
```

2021-01-12 22:56 UTC, ezgimez commented
let me startt... shall we

2021-01-12 23:22 UTC, ezgimez requested changes

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +\subsection{Baseline Trading}
trading?? do we have trading? isn't it gifting or smth

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +\begin{table}[htb]
hm.. the widths of the columns are not ideal.
can you enlarge the width of the very first column xxx

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +    \textbf{Archipelago Survivability}  &       \\
ok, let's be conssitent..
I think you should also include LINES in this table.... 
just like the table you have below :)

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +\label{subsec:Simulations:baseline:num_metrics}
oh god, good labellll

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +The purpose of performing simulations and analysing their results is to explore the efficacy of each agent's strategy under different conditions. We would like to answer questions such as: does the b
```suggestion
The purpose of performing simulations and analysing their results is to explore the efficacy of each agent's strategy under different conditions. We would like to answer questions such as: 

\begin{itemize}
\item Does the benefit of running the IIGO outweigh its cost? 
\item Can the agent strategies overcome the foraging dilemma outlined in Section INSERT REF LATER? 
\end{itemize}
 ```

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +The purpose of performing simulations and analysing their results is to explore the efficacy of each agent's strategy under different conditions. We would like to answer questions such as: does the b
could you include more questions PLZZ

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +The purpose of performing simulations and analysing their results is to explore the efficacy of each agent's strategy under different conditions. We would like to answer questions such as: does the b
```suggestion
The analysis encapsulates the purpose of the entire coursework and therefore, is the final result of all the work done. In this chapter, we aim to prove that our platform and the agents are capable of displaying interesting behaviour and hence, we can draw conclusions about how certain behaviours and environmental factors affect a multi-agent system.
```

I liked the last sentence -- good analysis

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +The purpose of performing simulations and analysing their results is to explore the efficacy of each agent's strategy under different conditions. We would like to answer questions such as: does the b
well ok GitHub didn't understand my intention, but it must be clear

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +To assist in this analysis we need to draw quantifiable results from the simulations. Thus enters the metrics: these numerical values give us information on the events of the game that we can then us
```suggestion
To assist in this analysis, we need to draw quantifiable results from the simulations. Thus enters the metrics: These numerical values give us information on the events of the game that we can then use to compare numerous simulations and draw insights into what influences the changing of certain parameters has on the game. Some metrics are also worth knowing on a turn by turn basis and as such have been represented as graphs. 
```

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +    \item \textbf{Island Resources$^1$$^2$}: Resource an island has each turn.
what is this ^1 ??

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +    \item \textbf{Island Resources$^1$$^2$}: Resource an island has each turn.
lol, do you wanna make a footnote or smth :D

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +    \item \textbf{Average Disaster Damage Mitigated(ADDM)}: Average disaster damage mitigated by the common pool.
```suggestion
    \item \textbf{Average Disaster Damage Mitigated (ADDM)}: Average disaster damage mitigated by the common pool.
```

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +    \item \textbf{Island Foraging Statistics(IFS)$^1$}: Resources an island has invested and gained from foraging.
```suggestion
    \item \textbf{Island Foraging Statistics (IFS)$^1$}: Amount of resources an island has invested and gained from foraging.
```

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +    \item \textbf{Archipelago Foraging Sustainability(AFS)}: The average net forage returns across all islands.
```suggestion
    \item \textbf{Archipelago Foraging Sustainability (AFS)}: The average net forage returns across all islands.
```

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +    \item \textbf{Archipelago Survivability}: Turns until all the islands in the archipelago die.
```suggestion
    \item \textbf{Archipelago Survivability}: Number of turns until all the islands in the archipelago die.
```

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +    \item \textbf{First Island Death}: Turns until any island dies.
```suggestion
    \item \textbf{First Island Death}: Number of turns until any island dies.
```

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +    \item \textbf{Island Resources$^1$$^2$}: Resource an island has each turn.
```suggestion
    \item \textbf{Island Resources$^1$$^2$}: Amount of resources an island has each turn.
```

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +    \item \textbf{Gini Index}: A measure of how fair the distribution of resources is across the archipelago.
good wording <3

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +    \item \textbf{Disasters Survived}: Number of disasters the archipelago has survived.
survived... meaning?
everyone survived or at least 1 island survived??
revise

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +    \item \textbf{Average Disaster Damage Mitigated(ADDM)}: Average disaster damage mitigated by the common pool.
```suggestion
    \item \textbf{Average Disaster Damage Mitigated(ADDM)}: Average amount of disaster damage mitigated by the common pool.
```

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +    \item \textbf{IIGO Roles$^2$}: The power each island has at any turn in the game. Power in this case is occupying one of the three roles in IIGO.
```suggestion
    \item \textbf{IIGO Roles$^2$}: The power each island has at any turn in the game\footnote{Power, in this case, refers to occupying one of the three roles in IIGO}.
```

or smth like that ..  fix my english plz

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +    \item \textbf{IIGO Allocations$^1$$^2$}: Amount of resources allocated to each island by the president and the amount the island has taken.
```suggestion
    \item \textbf{IIGO Allocations$^1$$^2$}: Amount of resources allocated to each island by the President and the amount the island has taken from the common pool.
```

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +    \item \textbf{IIGO Tax$^1$$^2$}: Amount of resources an island is expected to pay to the common pool for tax and amount the island has paid.
```suggestion
    \item \textbf{IIGO Tax$^1$$^2$}: Amount of resources an island is expected to contribute to the common pool in terms of tax and amount of tax an island has actually paid.
```

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +\small{$^1$ Presented on a per island basis. $^2$ Presented as a graph}
footnote plz

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +    \item \textbf{IIGO Sanctions$^1$$^2$}: Amount of resources an island is expected to pay to the common pool for sanctions and amount the island has paid.
```suggestion
    \item \textbf{IIGO Sanctions$^1$$^2$}: Amount of resources an island is expected to contribute to the common pool due to the imposed sanctions and amount of contribution the island has actually did for the imposed sanctions.
```

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +\small{$^1$ Presented on a per island basis. $^2$ Presented as a graph}
presented as a graph. 

full-stop svp

2021-01-12 23:22 UTC, ezgimez commented on 15_simulations/index.tex
> +In order to make any meaningful analysis one must first have a baseline from which to compare. In our case, this baseline is a \emph{normal} set of environment conditions which allows the agents to t
```suggestion
In order to make any meaningful analysis, one must first have a baseline against which to compare other performances. In our case, this baseline is a \emph{normal} set of environmental conditions which allows the agents to thrive for a significant period of time, chosen to be at around 100 turns. From this baseline, we can then start adjusting the configuration of the simulation by either making disasters more frequent and deadly or making resources more sparse.
```

2021-01-13 16:41 UTC, ezgimez commented on 15_simulations/index.tex
> +    \textbf{Archipelago Survivability}  &       \\
well ok LOL

2021-01-13 16:43 UTC, ezgimez commented
lgtm

although I don't like the inconsistency, due to time constraints,  I don't care about this at the moment

2021-01-13 16:44 UTC, ezgimez approved these changes

2021-01-13 16:44 UTC, merged